const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { JSDOM, VirtualConsole } = require(process.env.ATARA_JSDOM_PATH || '../backend/node_modules/jsdom');
const root = process.env.ATARA_PREVIEW_PATH || require('node:path').resolve(__dirname, '../preview');
const errors = [];
const console = new VirtualConsole(); console.on('jsdomError', e => errors.push(e));
const dom = new JSDOM(fs.readFileSync(`${root}/index.html`, 'utf8'), { url: 'https://atara.example/', runScripts: 'outside-only', virtualConsole: console });
const w = dom.window;
w.scrollTo = () => {};
w.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
w.HTMLDialogElement.prototype.close = function () { this.open = false; };
const ctx = dom.getInternalVMContext();
for (const name of ['ledger.js', 'app.js', 'pilot.js']) vm.runInContext(fs.readFileSync(`${root}/${name}`, 'utf8'), ctx, { filename: name });
assert.equal(errors.length, 0, errors.map(e => e.message).join('\n'));
const evalIn = source => vm.runInContext(source, ctx);
evalIn("show('home');");
w.document.getElementById('recipient').value = '@';
w.document.getElementById('recipient').dispatchEvent(new w.Event('input', { bubbles: true }));
assert.ok(w.document.querySelectorAll('.contact-suggestion').length >= 6);
evalIn("show('profile');");
assert.equal(w.document.querySelector('.bottom-nav [aria-current="page"]').dataset.screen, 'profile');
evalIn("AtaraLedger.expense(demoGroups[0], 'me', 'Dîner', '120'); refresh(); renderGroupDetail();");
assert.equal(evalIn("AtaraLedger.balances(demoGroups, 'me', 'marcuschen').owedToMe"), 0);
evalIn("demoGroups[0].expenses[0].splits.find(s => s.id === 'marcuschen').decision = 'accepted'; refresh(); renderGroupDetail();");
assert.equal(evalIn("AtaraLedger.balances(demoGroups, 'me', 'marcuschen').owedToMe"), 6000);
const repay = [...w.document.querySelectorAll('#groupDetailContent button')].find(b => b.textContent.includes('Simuler son remboursement'));
assert.ok(repay); repay.click();
[...w.document.querySelectorAll('dialog button')].find(b => b.textContent === 'Confirmer la simulation').click();
assert.equal(evalIn('state.balance'), 31000);
assert.equal(evalIn("AtaraLedger.balances(demoGroups, 'me', 'marcuschen').owedToMe"), 0);
assert.ok(w.document.getElementById('fullActivity').textContent.includes('Remboursement'));
// Create another vault; the original must remain intact.
w.document.getElementById('createInvite').value = '@demoami';
w.document.getElementById('createVaultForm').dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true }));
assert.equal(w.document.getElementById('pilot-vault-picker').options.length, 2);
const before = evalIn('state.balance');
w.document.getElementById('depositForm').dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true }));
assert.equal(evalIn('state.balance'), before, 'Deposits require every acceptance');
const picker = w.document.getElementById('pilot-vault-picker'); picker.value = '0'; picker.dispatchEvent(new w.Event('change'));
assert.equal(evalIn('state.vault'), 12500, 'Original vault balance preserved');
assert.equal(evalIn('state.contribution'), 5000);
w.document.getElementById('simulateOtherApprovals').click(); w.document.getElementById('confirmDeleteVault').click();
assert.equal(evalIn('state.balance'), before + 5000);
w.document.getElementById('confirmDeleteVault').click();
assert.equal(evalIn('state.balance'), before + 5000, 'No double refund');
assert.equal(errors.length, 0, errors.map(e => e.stack).join('\n'));
process.stdout.write('PASS: DOM initialization, @ contacts, navigation, acknowledged shares, settlement, Activity, multiple vaults, consent and refund replay.\n');
dom.window.close();
