const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");

const code = ts.transpileModule(
  fs.readFileSync(path.join(__dirname, "../utils/paymentRequest.ts"), "utf8"),
  {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  },
).outputText;
const paymentRequest = {};
new Function("exports", code)(paymentRequest);

test("decodes an ERC-20 EIP-681 transfer generated by the ATARA API", () => {
  const parsed = paymentRequest.parsePaymentRequest(
    "ethereum:0x1111111111111111111111111111111111111111@84532/transfer?address=0x2222222222222222222222222222222222222222&uint256=12500000",
  );

  assert.deepEqual(parsed, {
    address: "0x2222222222222222222222222222222222222222",
    amountInBaseUnits: "12500000",
    symbol: undefined,
    tokenAddress: "0x1111111111111111111111111111111111111111",
    chainId: 84532,
  });
  assert.equal(
    paymentRequest.baseUnitsToDecimal(parsed.amountInBaseUnits, 6),
    "12.5",
  );
});

test("keeps token amounts exact beyond JavaScript number precision", () => {
  const amount = "9007199254740993.123456";
  assert.equal(
    paymentRequest.decimalToBaseUnits(amount, 6),
    9007199254740993123456n,
  );
  assert.equal(
    paymentRequest.baseUnitsToDecimal("9007199254740993123456", 6),
    amount,
  );
});

test("rejects excess decimals and malformed base-unit values", () => {
  assert.equal(paymentRequest.decimalToBaseUnits("1.0000001", 6), null);
  assert.equal(paymentRequest.baseUnitsToDecimal("1e6", 6), null);
  assert.equal(paymentRequest.normalizeDecimalAmount("1,25"), "1.25");
});
